### ISSUE TITLE
consoles are inaccessible

### ISSUE THREAD

**Issue by do11** [mperezco/prometheus-rpm#1]
Your prometheus is run in `/var/lib/prometheus`, but consoles are in `/opt/prometheus/consoles` with `/opt/prometheus/console_libraries`, thus consoles are inaccessible. Please add into `/usr/lib/systemd/system/prometheus.service` `--web.console.templates=/opt/prometheus/consoles` and `--web.console.libraries=/opt/prometheus/console_libraries` or fix any other way.

**Comment by do11** [comment]
Thanks for your package, btw. Solution is found similar to this: https://github.com/prometheus/prometheus/issues/1540

**Comment by mmmmmmpc** [comment]
Consoles added ... still not working well. Will review when possible.
Version bumped.

**Comment by mmmmmmpc** [comment]
Updated packages in COPR
https://copr.fedorainfracloud.org/coprs/mperezco/prometheus/

**Comment by mmmmmmpc** [comment]
Fixed 2.1.0-8
Added default console.
Please update!

**Comment by do11** [comment]
Thanks much! (I don't think, though, that `index.html.example` should overwrite `index.html` with `cp`, since this is just example, and everybody supposed to put their own version of `index.html` tailored to their system.)

**Comment by mmmmmmpc** [comment]
https://github.com/mperezco/prometheus-rpm/issues/3

**Comment by mmmmmmpc** [comment]
Solved

**Comment by mmmmmmpc** [comment]
Uploaded to COPR
