### ISSUE TITLE
index.html.example should not overwrite index.html

### ISSUE THREAD

**Issue by mmmmmmpc** [mperezco/prometheus-rpm#3]
Thanks much! (I don't think, though, that index.html.example should overwrite index.html with cp, since this is just example, and everybody supposed to put their own version of index.html tailored to their system.)

**Comment by mmmmmmpc** [comment]
modified default index.html console to be handled like configuration file so it doesn't overwrite modified ones.

**Comment by do11** [comment]
Thanks again!
